version: '2.4'

services:
    MSSQL:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: mssql
        hostname: test_mssql
        ports:
            - "1433:1433"
        environment: 
            SA_PASSWORD: Beograd011!
            ACCEPT_EULA: "Y"
        volumes: 
            - "mssqldata:/var/lib/mssql"
        networks:
            - Test.MSSQL
  
volumes:
    mssqldata:

networks:
    Test.MSSQL: